### ISSUE TITLE
La valeur de `number_of_people` des groupes est parfois incorrecte

### ISSUE THREAD

**Issue by gregclermont** [ReseauEntourage/entourage-ror#194]
Les tables `entourages` et `tours` contiennent une colonne `number_of_people` qui est sensée refléter le nombre d’utilisateurs qui ont une `JoinRequest` acceptée (`status = 'accepted'`) pour ce groupe (Entourage ou Tour).

Ce compteur existe pour des raisons de performances, et il est affiché dans l’app.

On a observé que dans certaines situations la valeur de `number_of_people` n'est pas mise à jour correctement et ne reflète pas le nombre de membres du groupe.

## Objectifs
- [ ] Identifier les situations conduisant à une valeur incorrecte
- [ ] Écrire des tests pour ces situations
- [ ] Corriger l'implémentation pour résoudre les problèmes identifiés
- [x] Écrire une tâche rake permettant de corriger les valeurs pour les groupes existants (#195)
- [x] Écrire une tâche rake permettant de *lister* (sans corriger l'erreur) les groupes pour lesquels la valeur est incorrecte. Cette tâche sera exécutée à intervalle régulier en production pendant quelques semaines pour confirmer que le problème est bien résolu. (#195)

**Comment by Wykiki** [comment]
J'ai commencé par les tâches `rake`.

Elles remplissent la condition suivante : 
- les modèles `Entourage` / `Tour` qui ont des `join_requests` avec un `status` `accepted`

Pour avancer sur les trois premiers points, j'ai cette question : 
- quelles actions, que ce soit d'un point de vue DB / Model / Utilisateur, sont censees faire varier le compteur `number_of_people` ?

**Comment by gregclermont** [comment]
> quelles actions, que ce soit d'un point de vue DB / Model / Utilisateur, sont censees faire varier le compteur number_of_people ?

Au niveau technique : tout ce qui change le nombre de JoinRequest avec `status` `"accepted"`, donc
- création d’un JoinRequest avec le statut `accepted`
- suppression d’un JoinRequest ayant le statut `accepted`
- changer le statut d’une JoinRequest ayant le statut `accepted` vers un statut différent d’`accepted`
- changer le statut d’une JoinRequest ayant un statut différent d’`accepted` vers le statut `accepted`
(et potentiellement changer le joinable_type ou le joinable_id d’une JoinRequest ayant le statut `accepted`, mais on ne le fait jamais)

Dans la pratique, les cas les plus courants sont :
- un utilisateur crée un groupe (+1)
- le compte “Équipe Entourage” qu’on utilise pour la modération est ajouté automatiquement à toutes les nouvelles actions (+1)
- un utilisateur fait une demande pour rejoindre un groupe, puis celle-ci est acceptée par le propriétaire du groupe (+1)
- un utilisateur est invité à rejoindre un groupe, puis il accepte l’invitation (+1)
- un utilisateur membre du groupe quitte le groupe (-1)

Quelques cas particuliers
- un utilisateur fait une demande pour rejoindre un groupe qui a été créé par le compte “Équipe Entourage”, la demande est acceptée automatiquement après 15 secondes (+1)
- un utilisateur fait une demande pour rejoindre un groupe qui a l’attribut `public = true` (+1)

**Comment by gregclermont** [comment]
J’ai relancé la tâche rake aujourd’hui, et le bug qui est responsable de la majorité des erreurs semble être qu’on ne met pas à jour `number_of_people` quand on ajoute automatiquement le compte de l’équipe de modération à toutes les actions qui sont créées.

Le point d'entrée est ici :
https://github.com/ReseauEntourage/entourage-ror/blob/390371fc8f5ed0b948fab3a9569fd85e3450ed75/app/services/entourage_services/entourage_builder.rb#L72
